# config.yaml
user:
  account: ""
  password: ""
  # 如果设置了 encoded 之后 上面就输入你加密后的账号密码
  # 加密见文档 这里只做登陆用
  encoded: false
target: # todo
  # 需要的时间 单位 分钟
  time: 1000
  # 完成度 百分制
  finish: 30
  # 要刷的书的id 如果没有指定或者说是无效的 会在控制台手动选择
  book_id: 123456
# 请求超时时间 单位 秒
http-timeout: 10
# 下面的部分不懂就不动
base-url: "app.readoor.cn"

app-id: "1544059443"